version: '3.0'

services:
    nginx:
        image: nginx:alpine
        ports:
            - 80:80
            - 443:443
        volumes:
            - "./nginx-conf/nginx/conf.d:/etc/nginx/conf.d"
            - "./nginx-conf/nginx/ssl:/etc/nginx/ssl"
            - "./nginx-conf/nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./nginx-conf/log/nginx:/var/log/nginx"
            - "./www:/usr/share/nginx/html"
